
var app = new Vue({
    el: '#app',
    data() {
        return {
            message: 'Hello Vue!',
            searchText: "",
            tableData: [],
            initData: [
                { name: '付庄张振仓', money: 500 },
                { name: '109同学', money: 1000 },
                { name: '陈秀娟', money: 500 },
                { name: '高萍', money: 500 },
                { name: '马相梅', money: 500 },
                { name: '李坤', money: 500 },
                { name: '王利民', money: 500 },
                { name: '高庄神食一桌', money: 10000 },
                { name: '高庄存亮', money: 100 },
                { name: '高庄书民', money: 100 },
                { name: '贯申', money: 100 },
                { name: '贯超', money: 100 },
                { name: '贯力', money: 100 },
                { name: '灿勋', money: 200 },
                { name: '莹莹', money: 8000 },
                { name: '菲菲', money: 8000 },
                { name: '南京', money: 1000 },
                { name: '孙灿伟', money: 200 },
                { name: '陈文启', money: 50 },
                { name: '陈楼', money: 100 },
                { name: '巩义', money: 100 },
                { name: '孙同忠', money: 200 },
                { name: '孙贯奇', money: 100 },
                { name: '李庄', money: 200 },
                { name: '曹广建', money: 300 },
                { name: '孙瑞金', money: 100 },
                { name: '孙瑞珉', money: 500 },
                { name: '常庄史绪全', money: 500 },
                { name: '后陈', money: 100 },
                { name: '孙合忠', money: 200 },
                { name: '石木头', money: 100 },
                { name: '岳村邢庄', money: 100 },
                { name: '孙冠西', money: 200 },
                { name: '孙发青(原阳)', money: 100 },
                { name: '爱竹(原阳)', money: 100 },
                { name: '爱勤(原阳)', money: 100 },
                { name: '孙发林', money: 100 },
                { name: '胡楼', money: 100 },
                { name: '宋集', money: 100 },
                { name: '原阳凤娇', money: 100 },
                { name: '原阳凤玲', money: 100 },
                { name: '孙灿华', money: 50 },
                { name: '马刘庄', money: 100 },
                { name: '孙双玉', money: 200 },
                { name: '孙金玉', money: 200 },
                { name: '盛庄', money: 100 },
                { name: '孙贯玺', money: 200 },
                { name: '新楼', money: 100 },
                { name: '郑友祥 孙腾存等8人', money: 1600 },
                { name: '胡楼芳的', money: 100 },
                { name: '孙志海', money: 100 },
                { name: '王称固', money: 300 },
                { name: '张付原', money: 300 },
                { name: '孙边疆', money: 100 },
                { name: '瑞兰', money: 100 },
                { name: '瑞琴', money: 100 },
                { name: '于庄', money: 100 },
                { name: '小屯', money: 100 },
                { name: '侍郎寨', money: 100 },
                { name: '孙东生', money: 1000 },
                { name: '候晏林', money: 200 },
                { name: '李晋', money: 200 },
                { name: '叶广平', money: 100 },
                { name: '皮贵合', money: 200 },
                { name: '葛占林', money: 200 },
                { name: '王克山', money: 500 },
                { name: '王自红', money: 500 },
                { name: '王建立', money: 500 },
                { name: '东北庄', money: 100 },
                { name: '赵艳', money: 500 },
                { name: '栗广红', money: 1000 },
                { name: '高庄', money: 300 },
                { name: '三合村', money: 100 },
                { name: '三合村', money: 100 },
                { name: '顾子俊 郭兆峰 孙广增 谷海军 等', money: 2000 },
                { name: '任德显', money: 100 },
                { name: '后陈', money: 100 },
                { name: '侍郎寨', money: 100 },
                { name: '赵庙', money: 500 },
                { name: '马刘庄', money: 100 },
                { name: '马刘庄', money: 100 },
                { name: '胡楼', money: 100 },
                { name: '小屯', money: 100 },
                { name: '姜庄', money: 100 },
                { name: '七保寨', money: 1000 },
                { name: '于庄', money: 100 },
                { name: '梁庄', money: 2000 },
                { name: '十里庄,八里庄,郭龙', money: 600 },
                { name: '郑州陈楼', money: 400 },
                { name: '付庄', money: 100 },
                { name: '李庄', money: 200 },
                { name: '军寨', money: 100 },
                { name: '张密城', money: 100 },
                { name: '吴颖 李喜红 王梅格 高进英 郭玉华 王翠芹', money: 1200 },
                { name: '二厂', money: 100 },
                { name: '曹堂', money: 100 },
                { name: '韦庙', money: 100 },
                { name: '卜庄', money: 100 },
                { name: '孙密城', money: '神食一桌(需确认)' },
                { name: '铁发永', money: 200 },
                { name: '漫渡', money: 100 },
                { name: '孙密城', money: '神食一桌(礼洋100元)' },
                { name: '孙密城', money: '神食一桌' },
                { name: '姚庄', money: 200 },
                { name: '姚庄', money: 200 },
                { name: '姚庄', money: 200 },
                { name: '姚庄', money: 200 },
                { name: '姚庄', money: 3000 },
                { name: '姚庄刘继臣', money: 500 },
                { name: '彭忠峰', money: 1000 },
                { name: '孙广峰孙广奇马自洋', money: 600 },
                { name: '仝良军', money: 500 },
            ]
        }
    },
    methods: {
        doSearch() {
            console.log('searchTextsearchTextsearchText',this.searchText)
            if (_.isNil(this.searchText)) {
                this.tableData = _.cloneDeep(this.initData);
            } else {
                this.tableData = _.cloneDeep(this.initData.filter(a => a.name.indexOf(this.searchText) != -1))
            }
        }
    },
    created() {
        console.log('哒哒哒哒哒哒多多多多多多多多', _);
        this.tableData = _.cloneDeep(this.initData)
    }

});
